services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY,,}/backend:${GITHUB_SHA:-latest}
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY,,}/frontend:${GITHUB_SHA:-latest}
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge